services:
  - type: web
    name: arogyam-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 8000
    plan: free
